version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.0
    steps:
      - checkout
      - run: docker build -t platzi .

  test:
    docker:
      - image: circleci/node:8.1.0
    steps:
      - checkout
      - run: docker run platzi npm test
